name: kono
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  cloud_firestore: 4.17.3
  cloud_firestore_platform_interface: 6.2.3
  cloud_firestore_web: 3.12.3
  collection: 1.18.0
  firebase_core: 2.31.0
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.17.0
  firebase_performance: 0.9.4+5
  firebase_performance_platform_interface: 0.1.4+33
  firebase_performance_web: 0.1.6+5
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  intl: 0.19.0
  json_path: 0.7.2
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  stream_transform: 2.1.0
  timeago: 3.6.1
  url_launcher: 6.2.5
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2


dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  
